name: sounds-plugin
namespace: connectino
version: 0.0.3
author: Mojtaba Karimi
display_name: connectino-sound-plugins
description: This plugin install sounds for connectino-sound-plugins
homepage: https://github.com/connectino-platform/wazo-sounds-plugin.git
